/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface ChartJs {
    'data': any;
  }
  interface ChartJsAttributes extends StencilHTMLAttributes {
    'data'?: any;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ChartJs': Components.ChartJs;
  }

  interface StencilIntrinsicElements {
    'chart-js': Components.ChartJsAttributes;
  }


  interface HTMLChartJsElement extends Components.ChartJs, HTMLStencilElement {}
  var HTMLChartJsElement: {
    prototype: HTMLChartJsElement;
    new (): HTMLChartJsElement;
  };

  interface HTMLElementTagNameMap {
    'chart-js': HTMLChartJsElement
  }

  interface ElementTagNameMap {
    'chart-js': HTMLChartJsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
